### ISSUE TITLE
Timestamp error

### ISSUE THREAD

**Issue by networkshokunin** [liangleslie/nea_sg_weather#1]
Hi, 1st of all, thanks for making this SG Weather integration. I am running on 1.1.3-fix and encountering this error:

2022-01-23 13:27:28 WARNING (MainThread) [custom_components.nea_sg_weather] Unable to parse region data from coordinator, this could be temporary
2022-01-23 13:28:54 ERROR (MainThread) [custom_components.nea_sg_weather] Timeout making GET request from https://www.nea.gov.sg/api/Weather4DayOutlook/GetData/1642886929

If you can, could you take a look at this? Thanks!

**Comment by liangleslie** [comment]
Hey,

I would suggest that you move to v1.2.0 as 1.1.3-fix pulls from a less reliable API.

As for the error messages, these might be issues from the API endpoint, and they do pop up (though rarely) every once in a while. Without detailed debug details, it will be hard to fix, and it is likely that these might not be fixable if it is an API issue.

Do monitor the warning msgs for a while and report again if you notice them persisting. In that case you might need to enable debug logs for this component for detailed error message before submitting the issue.

**Comment by liangleslie** [comment]
Have released another temporary fix under v1.2.1-fix. 
This the NEA API is slightly less friendly and stable than the data.gov.sg API, so I would recommend to go back to a non-fix version of the component when the data.gov.sg service is back up.

**Comment by networkshokunin** [comment]
Awesome, thanks for the speedy update at this late hour!
