### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by sykong** [liangleslie/nea_sg_weather#13]
Been getting this error on Home Assistant 2023.4.2 (Frontend 20230406.1)

Is anyone facing the same issue?

==== logs ====
Logger: homeassistant.config_entries
Source: config_entries.py:942 
First occurred: 10:56:17 AM (1 occurrences) 
Last logged: 10:56:17 AM

Config entry 'Singapore Weather' for nea_sg_weather integration not ready yet: Update failed: division by zero; Retrying in background

**Comment by SeeThisIsMe** [comment]
Same problem for me. This integration hasn't worked for a few weeks now. 

![error](https://user-images.githubusercontent.com/53046241/232273318-5ae17d21-1e66-46f9-bfbd-7eab6797f4d7.JPG)

**Comment by sykong** [comment]
I realised this is the same as a closed issue and is due to data.gov.sg

https://github.com/liangleslie/nea_sg_weather/issues/6
