### ISSUE TITLE
Temperature & Humidity

### ISSUE THREAD

**Issue by jermisc** [liangleslie/nea_sg_weather#15]
I am wondering if there is an issue with the API at the moment?
The two data has remained constant since midnight (14 Aug). 

The rest seems to be working normally.

**Comment by acidpizza** [comment]
i think API has issues.. i curled `https://api.data.gov.sg/v1/environment/rainfall` directly and it gives nothing. Now all my rain sensors are in error state.

**Comment by jermisc** [comment]
thanks i figured it might be the API.

**Comment by liangleslie** [comment]
Try using the `alternate` releases ([v2.0.0-alternate](https://github.com/liangleslie/nea_sg_weather/releases/tag/v2.0.0-alternate)) as those scrape data from `weather.gov.sg` instead of using the `data.gov.sg` API endpoints.

Seems to be more reliable, though it's a hacky workaround.

**Comment by acidpizza** [comment]
wow i didn't know there was an alternate code. Switched to it and it's working now. Thanks!

**Comment by jermisc** [comment]
same here. alternate version is working.
Thank you @liangleslie !

**Comment by liangleslie** [comment]
> wow i didn't know there was an alternate code. Switched to it and it's working now. Thanks!

Didn't publicize it since it is not an API intended for developers use, and does some web scraping to get all the necessary data. It's more stable but it's probably designed for less load than the data.gov APIs...

**Comment by s0ftice** [comment]
I wrote in to data.gov.sg today and got the following response:

_Thank you for reaching out to us.
 
We are aware of this API issue, and our team is working to resolve it.
 
Cheers,
DataGov Team_

By the way, I'm also switched to 2.0.0-alternate for now, thanks for that! Unfortunately, HACS thinks 2.0.0 is newer and is bothering me to "update"...

Thanks!

**Comment by jermisc** [comment]
> I wrote in to data.gov.sg today and got the following response:
> 
> ```
> Thank you for reaching out to us.
>  
> We are aware of this API issue, and our team is working to resolve it.
>  
> Cheers,
> DataGov Team
> ```
> 
> By the way, I also switched to 2.0.0-alternate for now, thanks for that! Unfortunately, HACS thinks 2.0.0 is newer and is bothering me to "update"...
> 
> Thanks!

Now it's only temps and humidity working. everything else is down.

**Comment by s0ftice** [comment]
DataGov responded to my support ticket, updating that the API is back up and running.
I can confirm, looks good again.

Maybe a fall-back in the code would be nice (or an option to enable a fallback):
If NEA data from api.data.gov.sg unavailable, get it from weather.gov.sg instead.

Thanks
