### ISSUE TITLE
The nea_sg_weather integration is using deprecated forecast

### ISSUE THREAD

**Issue by s0ftice** [liangleslie/nea_sg_weather#18]
<img width="574" alt="image" src="https://github.com/liangleslie/nea_sg_weather/assets/44747731/5e408034-18aa-4e84-ad00-d6400b7cfad3">

The `forecast` state attribute is deprecated and will be removed in Home Assistant Core 2024.3, you should instead use the `weather.get_forecast` service.
(https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service)

not an urgent issue for now :)

**Comment by dexmorgan8888** [comment]
+1 same warning

**Comment by cwquek** [comment]
+1 😊

**Comment by liangleslie** [comment]
Thanks @kianhean for the pull request. closing this issue
