### ISSUE TITLE
Integration no longer working - 31st May 2024

### ISSUE THREAD

**Issue by Minniemie** [liangleslie/nea_sg_weather#29]
Hi there, 

The intergration is no longer pulling in data from NEA. Could you have a look please? Thank you kindly.

**Comment by borez** [comment]
To add on, the integration has an error upon loading: 

`Failed setup, will retry: Update failed: Expecting value: line 1 column 2 (char 1)`

Debug logs show that the nea_integration managed to pull data?

`2024-07-27 07:04:30.727 DEBUG (MainThread) [custom_components.nea_sg_weather] Finished fetching nea_sg_weather data in 0.468 seconds (success: False)`

On the following:
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

**Comment by liangleslie** [comment]
> To add on, the integration has an error upon loading:
> 
> `Failed setup, will retry: Update failed: Expecting value: line 1 column 2 (char 1)`
> 
> Debug logs show that the nea_integration managed to pull data?
> 
> `2024-07-27 07:04:30.727 DEBUG (MainThread) [custom_components.nea_sg_weather] Finished fetching nea_sg_weather data in 0.468 seconds (success: False)`
> 
> On the following: Core 2024.7.3 Supervisor 2024.06.2 Operating System 12.4 Frontend 20240710.0

I believe you were using the 2.3.0-alternate release?
Just released some quick fixes, should be working again
