### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MoonshineSG** [liangleslie/nea_sg_weather#3]
Few features that would be usfefull.

- support for current rain reading https://api.data.gov.sg/v1/environment/rainfall
- display "last update" on Lovelace card
- allow manual refresh ("update now" button on Lovelace)

**Comment by liangleslie** [comment]
These features are low priority for now.

1) rain sensors from data.gov are not very well named (a lot of sensors are given a sensor ID for their names and it is not clear where they are sited unless the user is able to decode the lat/lon) so it is not very usable except for advanced users who know which sensors they want to reference. Have not prioritized this, though advanced users could build a simple json sensor to poll for this and extract relevant locations using template sensors using existing platforms in HA.

2) this is a UI change and you will need to make a feature request to the maintainer of the weather card. The last updated info is already stored as an attribute in most sensors.

3) there is a update_entity core service in HA that should update the sensors and a custom service for this is not needed.

**Comment by MoonshineSG** [comment]
1. There is a map that displays the location of each sensor, even if it has a code as name. But no worries, a RestSensor in HA has solved my need to have the rain info. 
2. good to know
3. will give this a try. 


thanks!

**Comment by liangleslie** [comment]
@MoonshineSG - have added rainfall sensors into v1.4. not too sure how best to display this via the existing frontend, so it doesn't feel the most useful at the moment.

**Comment by MoonshineSG** [comment]
maybe can be used as sensor for automation

**Comment by liangleslie** [comment]
sure that is possible, but just note that the poll frequency is set to 15 min by default so it might not be sensitive enough to detect passing showers for automation. you could increase the frequency but i'm not sure if there are limits to the data.gov.sg API calls...
