### ISSUE TITLE
Animated weather 

### ISSUE THREAD

**Issue by chpeck** [liangleslie/nea_sg_weather#4]
Nice custom component! I just got it running and wondering what would be the easiest way to add animation to the weather map to show the direction the weather is moving.

**Comment by chpeck** [comment]
I open this PR. https://github.com/liangleslie/nea_sg_weather/pull/8

**Comment by liangleslie** [comment]
implemented, thanks.

**Comment by chpeck** [comment]
Nice one. I actually rewrote it to fetch all the previous images. Update to yours.
